### PR TITLE
 allows render_autoform to be called from View or Controller

### PR DESCRIPTION
**Pull request by Danwhy**
ref #7 

Detects which module is calling the function, and uses the appropriate `render` function

### CODE REVIEW

**Comment by Danwhy** [comment]
Travis has passed for this PR, not sure why it's not showing in Github:
screen shot 2018-10-01 at 16 43 11

**Comment by nelsonic** [comment]
@Danwhy I don't _see_ build `#17` on: https://travis-ci.org/dwyl/autoform/builds 😕 
image

Something we need to look into laters. 🔍 
Confident that this is working. happy to merge. 👍

**Review by nelsonic — APPROVED** [review]
@Danwhy looking great! 🎉

**Comment by nelsonic** [comment]
Build `#18` _passed_ on `master`:
image
https://travis-ci.org/dwyl/autoform/builds/435782612
image

**Pull request merged**
